#!/bin/bash

rm ~/.bash_alias*
rm ~/.bash_path
rm ~/.bash_vars
rm ~/.bashrc
rm ~/.gitconfig
rm ~/.inputrc
rm ~/.vimrc
rm ~/.tmux.conf
rm ~/tmux.conf

ln -s ~/{Developer/Dotfiles/,.}bashrc
ln -s ~/{Developer/Dotfiles/,.}gitconfig
ln -s ~/{Developer/Dotfiles/,.}inputrc
ln -s ~/{Developer/Dotfiles/,.}vimrc
ln -s ~/{Developer/Dotfiles/,.}tmux.conf
