#!/bin/bash

cwd=`pwd`

if [ "$#" -ne 0 ]; then cd "$1"; fi

grep Scale 0*/logfile > $cwd/sf.log &
grep lx1 0*/logfile > $cwd/lx1.log &
grep lx2 0*/logfile > $cwd/lx2.log &
grep NSTEPS 0*/logfile > $cwd/nsteps.log &
grep IOSTEP 0*/logfile > $cwd/iostep.log &
grep 'Step *1,' 0*/logfile > $cwd/step1.log &

cd $cwd

wait
