#!/bin/bash

IT_TI=xterm-256color-italic.terminfo

echo 'xterm-256color-italic|xterm with 256 colors and italic,' > $IT_TI
echo '    sitm=\E[3m, ritm=\E[23m,'                           >> $IT_TI
echo '            use=xterm-256color,'                        >> $IT_TI

tic xterm-256color-italic.terminfo
rm $IT_TI
