#!/bin/bash

# Listing script for wire analysis

case=`basename $(pwd)`;
mkdir ana;
ls 0*/avg*0.f* > ana/a.list
ls 0*/tmn*0.f* > ana/t.list
ln -s `pwd -p`/`ls 0*/restart*0.f* | head -1` `pwd -p`/ana/restart_0.f00001
