#!/bin/bash

mkdir nu

rm nu/*

for d in `ls -d ./*`
do
    cd $d
    for r in [0-9][0-9][0-9][0-9][0-9]
    do
        (cd $r && nu)
    done
    nuc
    cp nuc.csv ../nu/${d}.nuc.csv
    cd ..
done

