#!/bin/bash

mkdir nu 2> /dev/null

rm nu/* 2> /dev/null

for d in *053/
do
    cd $d

    for r in */
    do
        (cd $r && nu)
    done
    nuc
    cp nuc.csv ../nu/${d%/}.nuc.csv
    cd ..
done

